=== metadatacenter/cedar-model-validation-library/schema/template.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Meta-schema that describes the schema of a template",
    "type": "object",
    "properties": {
        "$schema": {
            "description": "Schema describing the JSON Schema '$schema' field in a template, element, and field",
            "type": "string", "format": "uri",
            "enum": [ "http://json-schema.org/draft-04/schema#" ]
        },
        "type": {
            "description": "Schema describing the JSON Schema 'type' field in a template, element, and field",
            "type": "string", "enum": [ "object", "array" ]
        },
        "schema:identifier": {
          "description": "Schema describing the template's user-defined identifier",
          "type": "string", "minLength": 1
        },
        "schema:name": {
            "description": "Schema describing the template name",
            "type": "string", "minLength": 1
        },
        "schema:description": {
            "description": "Schema describing the template description",
            "type": "string"
        },
        "title": {
            "description": "Schema describing the JSON Schema 'title' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "description": {
            "description": "Schema describing the JSON Schema 'description' field in a template, element, and field",
            "type": "string", "minLength": 1
        },
        "_ui": {
            "$ref": "#/definitions/templateUIFieldContent"
        },
        "@context": {
            "$ref": "#/definitions/templateJSONLDContextFieldContent"
        },
        "@id": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "@type": {
            "type": "string", "format": "uri",
            "enum": [ "https://schema.metadatacenter.org/core/Template" ]
        },
        "properties": {
            "$ref": "#/definitions/templatePropertiesFieldContent"
        },
        "required": {
            "$ref": "#/definitions/templateRequiredFieldContent"
        },
        "pav:createdOn": {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "pav:createdBy":  {
            "type": [ "string", "null" ], "format": "uri"
        },
        "pav:lastUpdatedOn":  {
            "type": [ "string", "null" ], "format": "date-time"
        },
        "oslc:modifiedBy": {
            "type": [ "string", "null" ], "format": "uri"
        },
        "additionalProperties": {
          "oneOf": [
            { "$ref": "file:falseOnlyAdditionalProperties.json" },
            { "$ref": "file:defaultObjectSchemaAdditionalProperties.json" }
          ]
        },
        "schema:schemaVersion": {
            "type": "string", "minLength": 1
        },
        "bibo:status": {
            "type": "string", "enum": [ "bibo:published", "bibo:draft" ]
        },
        "pav:version": {
            "type": "string", "minLength": 1
        },
        "pav:previousVersion": {
            "type": "string", "minLength": 1
        },
        "pav:derivedFrom": {
            "type": "string", "format": "uri"
        },
        "@nest": {
          "$ref": "#/definitions/nestFieldContent.json"
        }
    },
    "required": [ "$schema", "type", "title", "description", "_ui", "@context", "@id", "@type", "properties", "required",
        "pav:createdOn", "pav:createdBy", "pav:lastUpdatedOn", "oslc:modifiedBy", "schema:schemaVersion", "schema:name",
        "schema:description" ]
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/templates/static-field-template.json
{
  "@id": "https://repo.staging.metadatacenter.org/templates/671611bc-e560-494e-8326-50b7ae6602b7",
  "@type": "https://schema.metadatacenter.org/core/Template",
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "pav": "http://purl.org/pav/",
    "bibo": "http://purl.org/ontology/bibo/",
    "oslc": "http://open-services.net/ns/core#",
    "schema": "http://schema.org/",
    "schema:name": {
      "@type": "xsd:string"
    },
    "schema:description": {
      "@type": "xsd:string"
    },
    "pav:createdOn": {
      "@type": "xsd:dateTime"
    },
    "pav:createdBy": {
      "@type": "@id"
    },
    "pav:lastUpdatedOn": {
      "@type": "xsd:dateTime"
    },
    "oslc:modifiedBy": {
      "@type": "@id"
    }
  },
  "type": "object",
  "title": "Static field template template schema",
  "description": "Static field template template schema generated by the CEDAR Template Editor 2.1.11",
  "_ui": {
    "order": [
      "About Study Form"
    ],
    "propertyLabels": {
      "About Study Form": "About Study Form"
    },
    "propertyDescriptions": {
      "About Study Form": "Help Text"
    }
  },
  "properties": {
    "@context": {
      "type": "object",
      "properties": {
        "rdfs": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2000/01/rdf-schema#"
          ]
        },
        "xsd": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2001/XMLSchema#"
          ]
        },
        "pav": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://purl.org/pav/"
          ]
        },
        "schema": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://schema.org/"
          ]
        },
        "oslc": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://open-services.net/ns/core#"
          ]
        },
        "skos": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2004/02/skos/core#"
          ]
        },
        "rdfs:label": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "schema:isBasedOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "schema:name": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "schema:description": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "pav:createdOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:dateTime"
              ]
            }
          }
        },
        "pav:createdBy": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "pav:lastUpdatedOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:dateTime"
              ]
            }
          }
        },
        "oslc:modifiedBy": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "skos:notation": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "pav:derivedFrom": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        }
      },
      "required": [
        "xsd",
        "pav",
        "schema",
        "oslc",
        "schema:isBasedOn",
        "schema:name",
        "schema:description",
        "pav:createdOn",
        "pav:createdBy",
        "pav:lastUpdatedOn",
        "oslc:modifiedBy"
      ],
      "additionalProperties": false
    },
    "@id": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "@type": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "uniqueItems": true
        }
      ]
    },
    "schema:isBasedOn": {
      "type": "string",
      "format": "uri"
    },
    "schema:name": {
      "type": "string",
      "minLength": 1
    },
    "schema:description": {
      "type": "string"
    },
    "pav:createdOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "pav:createdBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "pav:lastUpdatedOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "oslc:modifiedBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "pav:derivedFrom": {
      "type": "string",
      "format": "uri"
    },
    "About Study Form": {
      "$schema": "http://json-schema.org/draft-04/schema#",
      "@id": "tmp-1542048003093-1835270",
      "@type": "https://schema.metadatacenter.org/core/StaticTemplateField",
      "@context": {
        "schema": "http://schema.org/",
        "pav": "http://purl.org/pav/",
        "bibo": "http://purl.org/ontology/bibo/",
        "oslc": "http://open-services.net/ns/core#"
      },
      "type": "object",
      "title": "About Study Form field schema",
      "description": "About Study Form field schema generated by the CEDAR Template Editor 2.1.11",
      "_ui": {
        "inputType": "richtext",
        "_content": "<p><i style=\"color: rgb(34, 34, 34); font-family: sans-serif; background-color: rgb(255, 255, 255);\">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</i></p>\n"
      },
      "pav:createdOn": null,
      "pav:createdBy": null,
      "pav:lastUpdatedOn": null,
      "oslc:modifiedBy": null,
      "schema:schemaVersion": "1.5.0",
      "schema:description": "Help Text",
      "additionalProperties": false,
      "schema:name": "About Study Form"
    }
  },
  "required": [
    "@context",
    "@id",
    "schema:isBasedOn",
    "schema:name",
    "schema:description",
    "pav:createdOn",
    "pav:createdBy",
    "pav:lastUpdatedOn",
    "oslc:modifiedBy"
  ],
  "schema:name": "Static Field Template",
  "schema:description": "",
  "pav:createdOn": "2018-11-12T10:38:57-0800",
  "pav:createdBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "pav:lastUpdatedOn": "2018-11-12T10:38:57-0800",
  "oslc:modifiedBy": "https://metadatacenter.org/users/018bbf94-f8e4-4e0e-946d-341698f70245",
  "schema:schemaVersion": "1.5.0",
  "additionalProperties": false,
  "pav:version": "0.0.1",
  "bibo:status": "bibo:draft",
  "$schema": "http://json-schema.org/draft-04/schema#"
}

=== metadatacenter/cedar-model-validation-library/src/test/resources/templates/check-characters/using-at.json
{
  "@id": "https://repo.metadatacenter.orgx/templates/82011b99-6784-458d-97ad-7438ca8f04c1",
  "@type": "https://schema.metadatacenter.org/core/Template",
  "@context": {
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "pav": "http://purl.org/pav/",
    "oslc": "http://open-services.net/ns/core#",
    "bibo": "http://purl.org/ontology/bibo/",
    "schema": "http://schema.org/",
    "schema:name": {
      "@type": "xsd:string"
    },
    "schema:description": {
      "@type": "xsd:string"
    },
    "pav:createdOn": {
      "@type": "xsd:dateTime"
    },
    "pav:createdBy": {
      "@type": "@id"
    },
    "pav:lastUpdatedOn": {
      "@type": "xsd:dateTime"
    },
    "oslc:modifiedBy": {
      "@type": "@id"
    }
  },
  "type": "object",
  "schema:name": "Single-Field Template",
  "schema:description": "Description",
  "title": "Single-field template template schema",
  "description": "Single-field template template schema autogenerated by the CEDAR Template Editor 1.0.7-SNAPSHOT",
  "_ui": {
    "pages": [],
    "order": [
      "@studyname"
    ],
    "propertyLabels": {},
    "propertyDescriptions": {}
  },
  "properties": {
    "@context": {
      "type": "object",
      "properties": {
        "rdfs": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2000/01/rdf-schema#"
          ]
        },
        "xsd": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2001/XMLSchema#"
          ]
        },
        "pav": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://purl.org/pav/"
          ]
        },
        "schema": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://schema.org/"
          ]
        },
        "oslc": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://open-services.net/ns/core#"
          ]
        },
        "skos": {
          "type": "string",
          "format": "uri",
          "enum": [
            "http://www.w3.org/2004/02/skos/core#"
          ]
        },
        "rdfs:label": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "schema:isBasedOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "schema:name": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "schema:description": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "pav:createdOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:dateTime"
              ]
            }
          }
        },
        "pav:createdBy": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "pav:lastUpdatedOn": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:dateTime"
              ]
            }
          }
        },
        "oslc:modifiedBy": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "@id"
              ]
            }
          }
        },
        "skos:notation": {
          "type": "object",
          "properties": {
            "@type": {
              "type": "string",
              "enum": [
                "xsd:string"
              ]
            }
          }
        },
        "@studyname": {
          "enum": [
            "https://schema.metadatacenter.orgx/properties/studyName"
          ]
        }
      },
      "required": [
        "xsd",
        "rdfs",
        "schema",
        "oslc",
        "pav",
        "skos",
        "rdfs:label",
        "schema:isBasedOn",
        "schema:name",
        "schema:description",
        "pav:createdOn",
        "pav:createdBy",
        "pav:lastUpdatedOn",
        "oslc:modifiedBy",
        "skos:notation",
        "@studyname"
      ],
      "additionalProperties": false
    },
    "@id": {
      "type": "string",
      "format": "uri"
    },
    "@type": {
      "oneOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "type": "string",
            "format": "uri"
          },
          "uniqueItems": true
        }
      ]
    },
    "schema:isBasedOn": {
      "type": "string",
      "format": "uri"
    },
    "schema:name": {
      "type": "string",
      "minLength": 1
    },
    "schema:description": {
      "type": "string"
    },
    "pav:createdOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "pav:createdBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "pav:lastUpdatedOn": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "oslc:modifiedBy": {
      "type": [
        "string",
        "null"
      ],
      "format": "uri"
    },
    "@studyname": {
      "@type": "https://schema.metadatacenter.org/core/TemplateField",
      "@context": {
        "xsd": "http://www.w3.org/2001/XMLSchema#",
        "pav": "http://purl.org/pav/",
        "oslc": "http://open-services.net/ns/core#",
        "schema": "http://schema.org/",
        "schema:name": {
          "@type": "xsd:string"
        },
        "schema:description": {
          "@type": "xsd:string"
        },
        "pav:createdOn": {
          "@type": "xsd:dateTime"
        },
        "pav:createdBy": {
          "@type": "@id"
        },
        "pav:lastUpdatedOn": {
          "@type": "xsd:dateTime"
        },
        "oslc:modifiedBy": {
          "@type": "@id"
        }
      },
      "type": "object",
      "schema:name": "Study Name",
      "schema:description": "",
      "title": "Study name field schema",
      "description": "Study name field schema autogenerated by the CEDAR Template Editor",
      "_ui": {
        "inputType": "textfield"
      },
      "_valueConstraints": {
        "requiredValue": true
      },
      "properties": {
        "@type": {
          "oneOf": [
            {
              "type": "string",
              "format": "uri"
            },
            {
              "type": "array",
              "minItems": 1,
              "items": {
                "type": "string",
                "format": "uri"
              },
              "uniqueItems": true
            }
          ]
        },
        "@value": {
          "type": [
            "string",
            "null"
          ]
        },
        "rdfs:label": {
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "@value"
      ],
      "pav:createdOn": "2017-05-19T11:47:46-0700",
      "pav:createdBy": "https://metadatacenter.org/users/67a894dc-e9df-42d0-bb6e-5dbb4aa9dd79",
      "pav:lastUpdatedOn": "2017-05-19T11:47:46-0700",
      "oslc:modifiedBy": "https://metadatacenter.org/users/67a894dc-e9df-42d0-bb6e-5dbb4aa9dd79",
      "schema:schemaVersion": "1.1.0",
      "additionalProperties": false,
      "@id": "https://repo.metadatacenter.orgx/template-fields/ef0927d6-1ca1-48c5-944a-5a6cebb4201e",
      "$schema": "http://json-schema.org/draft-04/schema#"
    }
  },
  "required": [
    "@context",
    "@id",
    "schema:isBasedOn",
    "schema:name",
    "schema:description",
    "pav:createdOn",
    "pav:createdBy",
    "pav:lastUpdatedOn",
    "oslc:modifiedBy",
    "@studyname"
  ],
  "pav:createdOn": "2017-05-19T11:47:46-0700",
  "pav:createdBy": "https://metadatacenter.org/users/67a894dc-e9df-42d0-bb6e-5dbb4aa9dd79",
  "pav:lastUpdatedOn": "2017-05-19T11:47:46-0700",
  "oslc:modifiedBy": "https://metadatacenter.org/users/67a894dc-e9df-42d0-bb6e-5dbb4aa9dd79",
  "schema:schemaVersion": "1.4.0",
  "bibo:status": "bibo:draft",
  "pav:version": "0.0.1",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/draft-04/schema#"
}
